//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JewelryStore.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartItem
    {
        public int IdCartItem { get; set; }
        public Nullable<int> IdJewelry { get; set; }
        public Nullable<int> IdUser { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<System.DateTime> AddedData { get; set; }
    
        public virtual Jewelry Jewelry { get; set; }
        public virtual User User { get; set; }
    }
}
