//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JewelryStore.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jewelry
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Jewelry()
        {
            this.Order = new HashSet<Order>();
            this.OrderItem = new HashSet<OrderItem>();
            this.CartItem = new HashSet<CartItem>();
        }
    
        public int IdJewelry { get; set; }
        public string NameJewelry { get; set; }
        public Nullable<int> IdJewelryTip { get; set; }
        public Nullable<int> IdMaterial { get; set; }
        public Nullable<int> IdStone { get; set; }
        public Nullable<int> IdSupplier { get; set; }
        public Nullable<int> PriceJewelry { get; set; }
        public string ImagePath { get; set; }
    
        public virtual JewelryTip JewelryTip { get; set; }
        public virtual Material Material { get; set; }
        public virtual Stone Stone { get; set; }
        public virtual Supplier Supplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderItem> OrderItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CartItem> CartItem { get; set; }
    }
}
